version: '3'

services:
            
    audio-services:
        restart: always
        container_name : audio-services
        build: ./audio-services
        tty: true
        ports: 
            - '9003:8081'

        volumes:
          - type: bind
            source : E:\python-code\Rockstar\audio-services
            target : /home/shared-files

          - type: bind
            source : E:\python-code\Rockstar\volume
            target : /home/shared-files/code/uploads

        depends_on:
            - db-mysql

    stream-service:
        restart: always
        container_name : stream-service
        build: ./stream-service
        tty: true
        ports: 
            - '9004:8081'

        volumes:
          - type: bind
            source : E:\python-code\Rockstar\stream-service
            target : /home/shared-files

          - type: bind
            source : E:\python-code\Rockstar\volume
            target : /home/shared-files/code/music



networks:
    net:
        ipam:
            driver: default
            config:
                - subnet: 212.172.1.0/30
    host:
        name: host
        external: true


