version: '3'

services:

    audio-services:
        restart: always
        container_name : audio-services
        build: ./audio-services
        tty: true
        ports: 
            - '9003:8081'

        volumes:
          - type: bind
            source : E:\python-code\Rockstar\audio-services
            target : /home/shared-files

          - type: bind
            source : E:\python-code\Rockstar\volume
            target : /home/shared-files/code/uploads

        depends_on:
            - db-mysql

    stream-service:
        restart: always
        container_name : stream-service
        build: ./stream-service
        tty: true
        ports: 
            - '9004:8081'

        volumes:
          - type: bind
            source : E:\python-code\Rockstar\stream-service
            target : /home/shared-files

          - type: bind
            source : E:\python-code\Rockstar\volume
            target : /home/shared-files/code/music
        depends_on:
            - db-mysql
            
    db-mysql:
        image: mariadb
        restart: always
        container_name : db-music
        ports: 
            - '3306:3306'

        environment:
            MARIADB_ROOT_PASSWORD: pwd
            MARIADB_DATABASE : audio_service
            MARIADB_USER : user
            MARIADB_PASSWORD : password
        #avoid error for STRICT_TRANS_TABLES (error was thrown if no default value was assigned to primary key)
        command: mysqld --sql_mode=""

        expose:
            - '3306:3306'
        volumes:
          # persist data files into `datadir` volume managed by docker
          - datadir:/var/lib/mysql
          # bind-mount any sql files that should be run while initializing
          - ./tables.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
    datadir:
    
networks:
    net:
        ipam:
            driver: default
            config:
                - subnet: 212.172.1.0/30
    host:
        name: host
        external: true


