version: '3'

services:

    db-mysql:
        image: mysql/mysql-server:latest
        restart: always
        container_name : db-music
        ports: 
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: pwd
            MYSQL_DATABASE : audio_service
            MYSQL_USER : user
            MYSQL_PASSWORD : password
        expose:
            - '3306:3306'
        volumes:
          - type: bind
            source : E:\python-code\Rockstar\volume\mysql
            target : /var/lib/mysql


    stream-service:
        restart: always
        container_name : stream-service
        build: ./stream-service
        tty: true
        ports: 
            - '9003:8081'

        volumes:
          - type: bind
            source : E:\python-code\Rockstar\stream-service
            target : /home/shared-files

          - type: bind
            source : E:\python-code\Rockstar\volume
            target : /home/shared-files/code/music

        depends_on:
            - db-mysql


networks:
    net:
        ipam:
            driver: default
            config:
                - subnet: 212.172.1.0/30
    host:
        name: host
        external: true


